/// 常见 Android 应用包名 → 应用名称映射
/// 覆盖中国大陆、港澳台及国际主流应用
const Map<String, String> kAppNames = {
  // === 社交通讯 ===
  'com.tencent.mm': '微信',
  'com.tencent.mobileqq': 'QQ',
  'com.tencent.tim': 'TIM',
  'com.alibaba.android.rimet': '钉钉',
  'com.ss.android.lark': '飞书',
  'com.tencent.wework': '企业微信',
  'com.xunmeng.pdd': '拼多多',
  'com.ss.android.ugc.aweme': '抖音',
  'com.smile.gifmaker': '快手',
  'com.ss.android.ugc.aweme.lite': '抖音极速版',
  'com.kwai.video': '快手',
  'com.kuaishou.nebula': '快手极速版',
  'com.tencent.qqlive': '腾讯视频',
  'com.youku.phone': '优酷',
  'tv.danmaku.bili': '哔哩哔哩',
  'com.duowan.kiwi': '虎牙直播',
  'com.douyu.mobile': '斗鱼',
  'com.weico.international': '微博',
  'com.sina.weibo': '微博',
  'com.zhihu.android': '知乎',
  'com.xiaomi.mico': '小爱同学',
  'com.tencent.qqmusic': 'QQ音乐',
  'com.kugou.android': '酷狗音乐',
  'com.kuwo.player': '酷我音乐',
  'com.netease.cloudmusic': '网易云音乐',
  'cn.com.chinatelecom.account': '电信营业厅',

  // === 支付购物 ===
  'com.eg.android.AlipayGphone': '支付宝',
  'com.taobao.taobao': '淘宝',
  'com.tmall.wireless': '天猫',
  'com.jingdong.app.mall': '京东',
  'com.pinduoduo.xlogistics': '拼多多',
  'com.xunmeng.pinduoduo': '拼多多',
  'com.sankuai.meituan': '美团',
  'com.sankuai.elephant': '大象',
  'me.ele': '饿了么',
  'ele.me': '饿了么',
  'com.dianping.v1': '大众点评',
  'com.xiaomi.shop': '小米商城',
  'com.suning.mobile.ebuy': '苏宁易购',
  'com.vipshop.vop.mobile': '唯品会',
  'com.jingdong.pdj': '京东到家',
  'com.dangdang.buy2': '当当',
  'com.wuba.zhuanzhuan': '转转',
  'com.goat.server': '得物',
  'com.shizhuang.duapp': '得物',
  'com.smk': '什么值得买',

  // === 出行导航 ===
  'com.autonavi.minimap': '高德地图',
  'com.baidu.BaiduMap': '百度地图',
  'com.tencent.map': '腾讯地图',
  'com.sdu.didi.psnger': '滴滴出行',
  'com.huancheng.faloo': '哈啰出行',
  'com.meituan.taxi': '美团打车',
  'ctrip.android.view': '携程旅行',
  'com.Qunar': '去哪儿旅行',
  'com.tuniu.app.ui': '途牛旅游',
  'com.mafengwo.travel': '马蜂窝',
  'com.sinovatech.unicom.ui': '联通营业厅',
  'com.greenpoint.client': '中国移动',

  // === 办公工具 ===
  'com.tencent.wps': 'WPS Office',
  'cn.wps.moffice_eng': 'WPS Office',
  'com.microsoft.office.outlook': 'Outlook',
  'com.microsoft.teams': 'Teams',
  'com.microsoft.office.word': 'Word',
  'com.microsoft.office.excel': 'Excel',
  'com.microsoft.office.powerpoint': 'PowerPoint',
  'com.google.android.apps.docs': 'Google Docs',
  'com.google.android.apps.slides': 'Google Slides',
  'com.google.android.apps.sheets': 'Google Sheets',
  'com.baidu.netdisk': '百度网盘',
  'com.tencent.qcloud': '腾讯微云',
  'com.alicloud.databox': '阿里云盘',
  'com.xiaomi.market': '应用商店',

  // === 系统工具 ===
  'com.android.settings': '设置',
  'com.android.systemui': '系统界面',
  'com.android.launcher3': '桌面',
  'com.android.browser': '浏览器',
  'com.android.camera': '相机',
  'com.android.camera2': '相机',
  'com.android.gallery3d': '图库',
  'com.android.music': '音乐',
  'com.android.vending': 'Google Play',
  'com.android.contacts': '通讯录',
  'com.android.dialer': '电话',
  'com.android.mms': '信息',
  'com.android.calculator2': '计算器',
  'com.android.calendar': '日历',
  'com.android.deskclock': '时钟',
  'com.android.soundrecorder': '录音机',
  'com.android.filemanager': '文件管理',
  'com.android.documentsui': '文件',
  'com.android.inputmethod.latin': '键盘',
  'com.android.providers.downloads.ui': '下载',
  'com.android.email': '邮件',
  'com.android.nfc': 'NFC',
  'com.android.bluetooth': '蓝牙',
  'com.android.wallpaper': '壁纸',

  // === 小米 MIUI ===
  'com.miui.home': '小米桌面',
  'com.miui.gallery': '相册',
  'com.miui.camera': '相机',
  'com.miui.weather2': '天气',
  'com.miui.calculator': '计算器',
  'com.miui.notes': '便签',
  'com.miui.cleanmaster': '垃圾清理',
  'com.miui.powerkeeper': '电量与性能',
  'com.miui.msa.global': '系统广告',
  'com.miui.android.fashiongallery': '个性主题',
  'com.miui.screenrecorder': '屏幕录制',
  'com.miui.compass': '指南针',
  'com.miui.voiceassist': '小爱同学',
  'com.miui.yellowpage': '生活黄页',
  'com.miui.virtualsim': '小米移动',
  'com.miui.daemon': 'MIUI 服务',
  'com.miui.micloudsync': '小米云同步',
  'com.miui.personalassistant': '智能助理',
  'com.miui.smarttravel': '智能出行',
  'com.xiaomi.scanner': '扫一扫',
  'com.xiaomi.gamecenter': '游戏中心',
  'com.xiaomi.drivemode': '驾车模式',
  'com.xiaomi.payment': '小米支付',
  'com.xiaomi.midrop': '小米互传',
  'com.xiaomi.mircs': '小米漫游',
  'com.xiaomi.finddevice': '查找设备',
  'com.xiaomi.xmsf': '小米服务框架',

  // === 华为 EMUI / HarmonyOS ===
  'com.huawei.systemmanager': '手机管家',
  'com.huawei.appmarket': '华为应用市场',
  'com.huawei.browser': '华为浏览器',
  'com.huawei.himovie': '华为视频',
  'com.huawei.hifolder': '华为文件管理',
  'com.huawei.camera': '华为相机',
  'com.huawei.gallery': '华为相册',
  'com.huawei.music': '华为音乐',
  'com.huawei.android.totemweather': '华为天气',
  'com.huawei.android.launcher': '华为桌面',
  'com.huawei.contactscamcard': '华为通讯录',
  'com.huawei.compass': '指南针',
  'com.huawei.parentcontrol': '学生模式',
  'com.huawei.hiai': 'HiAI',
  'com.huawei.hwid': '华为账号',
  'com.huawei.hicloud': '华为云空间',

  // === OPPO ColorOS ===
  'com.heytap.market': '软件商店',
  'com.heytap.browser': '浏览器',
  'com.heytap.music': '音乐',
  'com.heytap.video': '视频',
  'com.heytap.cloud': '云服务',
  'com.coloros.weather': '天气',
  'com.coloros.gallery3d': '相册',
  'com.coloros.camera': '相机',
  'com.coloros.filemanager': '文件管理',
  'com.coloros.calculator': '计算器',
  'com.coloros.clock': '时钟',
  'com.coloros.soundrecorder': '录音',
  'com.oppo.market': '应用商店',
  'com.oppo.camera': '相机',

  // === vivo FuntouchOS ===
  'com.bbk.appstore': 'vivo 应用商店',
  'com.bbk.browser': 'vivo 浏览器',
  'com.bbk.calendar': '日历',
  'com.bbk.clock': '时钟',
  'com.bbk.camera': 'vivo 相机',
  'com.vivo.gallery': 'vivo 相册',
  'com.vivo.weather': '天气',
  'com.vivo.filemanager': '文件管理',
  'com.vivo.calculator': '计算器',
  'com.vivo.soundrecorder': '录音机',
  'com.vivo.compass': '指南针',

  // === 三星 One UI ===
  'com.sec.android.app.camera': 'Samsung 相机',
  'com.sec.android.gallery3d': 'Samsung 相册',
  'com.sec.android.app.music': 'Samsung 音乐',
  'com.sec.android.app.browser': 'Samsung 浏览器',
  'com.samsung.android.calendar': 'Samsung 日历',
  'com.samsung.android.app.notes': 'Samsung 笔记',
  'com.samsung.android.app.tips': '提示',
  'com.samsung.android.voc': 'Samsung Members',
  'com.samsung.android.app.galaxyfinder': '搜索',
  'com.samsung.android.themestore': '主题商店',
  'com.samsung.android.game.gamehome': '游戏启动器',
  'com.samsung.android.messaging': '信息',
  'com.samsung.android.dialer': '电话',
  'com.samsung.android.contacts': '通讯录',
  'com.samsung.android.clockpack': '时钟',
  'com.samsung.android.app.clockpack': '时钟',

  // === Google 应用 ===
  'com.google.android.apps.maps': 'Google 地图',
  'com.google.android.gms': 'Google 服务',
  'com.google.android.gm': 'Gmail',
  'com.google.android.youtube': 'YouTube',
  'com.google.android.apps.photos': 'Google 相册',
  'com.google.android.apps.translate': 'Google 翻译',
  'com.google.android.GoogleCamera': 'Google 相机',
  'com.google.android.calculator': 'Google 计算器',
  'com.google.android.calendar': 'Google 日历',
  'com.google.android.keep': 'Keep',
  'com.google.android.dialer': 'Google 电话',
  'com.google.android.contacts': 'Google 通讯录',
  'com.google.android.messaging': 'Google 信息',
  'com.google.android.apps.nbu.files': 'Google 文件',
  'com.google.android.apps.wallet': 'Google 钱包',
  'com.google.android.apps.meetings': 'Google Meet',
  'com.google.android.projection.gearhead': 'Android Auto',
  'com.google.android.apps.chromecast.app': 'Google Home',
  'com.google.android.apps.fitness': 'Google Fit',
  'com.google.stadia.android': 'Stadia',

  // === 浏览器 ===
  'com.android.chrome': 'Chrome',
  'com.google.android.chrome': 'Chrome',
  'com.brave.browser': 'Brave',
  'org.mozilla.firefox': 'Firefox',
  'com.microsoft.emmx': 'Edge',
  'com.UCMobile': 'UC浏览器',
  'com.UCMobile.x86': 'UC浏览器',
  'com.tencent.qqbrowser': 'QQ浏览器',
  'com.baidu.searchbox': '百度',
  'com.sogou.search': '搜狗搜索',
  'mark.via': 'Via浏览器',
  'com.kkshine.browser': '夸克浏览器',
  'com.quark.browser': '夸克浏览器',

  // === 新闻阅读 ===
  'com.ss.android.article.news': '今日头条',
  'com.ss.android.article.lite': '今日头条极速版',
  'com.netease.newsreader': '网易新闻',
  'com.tencent.news': '腾讯新闻',
  'com.sohu.news': '搜狐新闻',
  'com.ifeng.news2': '凤凰新闻',
  'com.dragon.read': '番茄免费小说',
  'com.ifreetalk.ftreader': '七猫小说',
  'com.chaozh.iReader': '掌阅',
  'com.sfacg': '菠萝包轻小说',

  // === 游戏平台 ===
  'com.tencent.tmgp.sgame': '王者荣耀',
  'com.tencent.tmgp.pubgmhd': '和平精英',
  'com.tencent.jgm': '金铲铲之战',
  'com.tencent.lolm': '英雄联盟手游',
  'com.tencent.tmgp.cf': '穿越火线',
  'com.tencent.tmgp.qjnn': '欢乐斗地主',
  'com.tencent.tmgp.weiqi': '天天象棋',
  'com.netease.hyxd': '荒野行动',
  'com.netease.mrzh': '明日之后',
  'com.miHoYo.Yuanshen': '原神',
  'com.miHoYo.enterprise.NGHSoD': '崩坏：星穹铁道',
  'com.miHoYo.bh3.oversea': '崩坏3',
  'com.miHoYo.bh3china': '崩坏3',
  'com.KiwiWalks.WitchSpring': '魔女之泉',
  'com.supercell.clashofclans': '部落冲突',
  'com.supercell.magic': '皇室战争',
  'com.ea.game.pvz2': '植物大战僵尸2',

  // === 学习教育 ===
  'com.chaoxing.mobile': '学习通',
  'com.xueersi.ilearn': '学而思',
  'com.baidu.wenku': '百度文库',
  'cn.com.open.mooc': '中国大学MOOC',
  'com.netease.edu.ucmooc': '网易公开课',
  'com.hujiang.hjclass': '沪江网校',

  // === 健康运动 ===
  'com.xiaomi.wearable': '小米穿戴',
  'com.xiaomi.hm.health': 'Zepp Life',
  'com.keep.mobile': 'Keep',
  'com.codoon.gps': '咕咚',
  'com.xinlukj.plotfitness': '乐动力',

  // === 常用国际应用 ===
  'com.whatsapp': 'WhatsApp',
  'com.instagram.android': 'Instagram',
  'com.facebook.katana': 'Facebook',
  'com.facebook.orca': 'Messenger',
  'com.twitter.android': 'X (Twitter)',
  'com.zhiliaoapp.musically': 'TikTok',
  'com.snapchat.android': 'Snapchat',
  'com.linkedin.android': 'LinkedIn',
  'com.pinterest': 'Pinterest',
  'com.spotify.music': 'Spotify',
  'com.netflix.mediaclient': 'Netflix',
  'com.amazon.mShop.android.shopping': 'Amazon',
  'com.ubercab': 'Uber',
  'com.airbnb.android': 'Airbnb',
  'com.skype.raider': 'Skype',
  'com.telegram.messenger': 'Telegram',
  'org.telegram.messenger': 'Telegram',
  'com.discord': 'Discord',
  'com.viber.voip': 'Viber',
  'com.linecorp.LINE': 'LINE',
  'com.kakao.talk': 'KakaoTalk',
  'jp.naver.line.android': 'LINE',

  // === 开发工具 ===
  'com.termux': 'Termux',
  'stericson.busybox': 'BusyBox',
  'eu.chainfire.supersu': 'SuperSU',
  'com.topjohnwu.magisk': 'Magisk',
};
