/// 权限名称中文映射 — 按 key 排序，方便查找
const kPermissionNames = <String, String>{
  // ===== android.permission.* =====
  'android.permission.ACCESS_BACKGROUND_LOCATION': '后台位置访问',
  'android.permission.ACCESS_COARSE_LOCATION': '粗略位置',
  'android.permission.ACCESS_FINE_LOCATION': '精确位置',
  'android.permission.ACCESS_LOCATION_EXTRA_COMMANDS': '额外定位命令',
  'android.permission.ACCESS_MEDIA_LOCATION': '媒体位置',
  'android.permission.ACCESS_NETWORK_STATE': '网络状态',
  'android.permission.ACCESS_NOTIFICATION_POLICY': '勿扰模式',
  'android.permission.ACCESS_WIFI_STATE': 'WiFi 状态',
  'android.permission.ACTIVITY_RECOGNITION': '活动识别',
  'android.permission.ADD_VOICEMAIL': '添加语音邮件',
  'android.permission.ANSWER_PHONE_CALLS': '接听电话',
  'android.permission.AUTHENTICATE_ACCOUNTS': '验证账户',
  'android.permission.BATTERY_STATS': '电池统计',
  'android.permission.BIND_APPWIDGET': '绑定桌面小部件',
  'android.permission.BIND_DEVICE_ADMIN': '设备管理员',
  'android.permission.BIND_NOTIFICATION_LISTENER_SERVICE': '通知监听',
  'android.permission.BIND_VPN_SERVICE': 'VPN 服务',
  'android.permission.BLUETOOTH': '蓝牙',
  'android.permission.BLUETOOTH_ADMIN': '蓝牙管理',
  'android.permission.BLUETOOTH_ADVERTISE': '蓝牙广播',
  'android.permission.BLUETOOTH_CONNECT': '蓝牙连接',
  'android.permission.BLUETOOTH_SCAN': '蓝牙扫描',
  'android.permission.BODY_SENSORS': '身体传感器',
  'android.permission.BODY_SENSORS_BACKGROUND': '后台身体传感器',
  'android.permission.BROADCAST_STICKY': '发送粘性广播',
  'android.permission.CALL_PHONE': '拨打电话',
  'android.permission.CALL_PRIVILEGED': '拨号（系统）',
  'android.permission.CAMERA': '相机',
  'android.permission.CHANGE_CONFIGURATION': '更改系统配置',
  'android.permission.CHANGE_NETWORK_STATE': '更改网络状态',
  'android.permission.CHANGE_WIFI_MULTICAST_STATE': 'WiFi 组播',
  'android.permission.CHANGE_WIFI_STATE': '更改 WiFi 状态',
  'android.permission.CLEAR_APP_CACHE': '清除应用缓存',
  'android.permission.DELETE_PACKAGES': '删除应用',
  'android.permission.DETECT_SCREEN_CAPTURE': '屏幕截图检测',
  'android.permission.DEVICE_POWER': '设备电源',
  'android.permission.DISABLE_KEYGUARD': '禁用锁屏',
  'android.permission.DUMP': '系统转储',
  'android.permission.EXPAND_STATUS_BAR': '展开状态栏',
  'android.permission.FLASHLIGHT': '闪光灯',
  'android.permission.FOREGROUND_SERVICE': '前台服务',
  'android.permission.FOREGROUND_SERVICE_CAMERA': '前台相机服务',
  'android.permission.FOREGROUND_SERVICE_CONNECTED_DEVICE': '前台连接设备服务',
  'android.permission.FOREGROUND_SERVICE_DATA_SYNC': '前台数据同步服务',
  'android.permission.FOREGROUND_SERVICE_HEALTH': '前台健康服务',
  'android.permission.FOREGROUND_SERVICE_LOCATION': '前台定位服务',
  'android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK': '前台媒体播放服务',
  'android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION': '前台投屏服务',
  'android.permission.FOREGROUND_SERVICE_MICROPHONE': '前台麦克风服务',
  'android.permission.FOREGROUND_SERVICE_PHONE_CALL': '前台通话服务',
  'android.permission.FOREGROUND_SERVICE_SPECIAL_USE': '前台特殊用途服务',
  'android.permission.GET_ACCOUNTS': '获取账户',
  'android.permission.GET_ACCOUNTS_PRIVILEGED': '获取账户（特权）',
  'android.permission.GET_TASKS': '获取任务',
  'android.permission.GLOBAL_SEARCH': '全局搜索',
  'android.permission.HIGH_SAMPLING_RATE_SENSORS': '高采样率传感器',
  'android.permission.INSTALL_PACKAGES': '安装应用',
  'android.permission.INSTALL_SHORTCUT': '创建快捷方式',
  'android.permission.INTERNET': '互联网访问',
  'android.permission.KILL_BACKGROUND_PROCESSES': '结束后台进程',
  'android.permission.MANAGE_ACCOUNTS': '管理账户',
  'android.permission.MANAGE_DEVICE_POLICY_ACCESSIBILITY': '无障碍策略管理',
  'android.permission.MANAGE_EXTERNAL_STORAGE': '管理外部存储',
  'android.permission.MANAGE_MEDIA': '媒体管理',
  'android.permission.MANAGE_ONGOING_CALLS': '管理进行中的通话',
  'android.permission.MANAGE_WIFI_NETWORKS': 'WiFi 网络管理',
  'android.permission.MEDIA_CONTENT_CONTROL': '媒体内容控制',
  'android.permission.MODIFY_AUDIO_SETTINGS': '修改音频设置',
  'android.permission.MOUNT_UNMOUNT_FILESYSTEMS': '挂载文件系统',
  'android.permission.NEARBY_WIFI_DEVICES': '附近 WiFi 设备',
  'android.permission.NFC': 'NFC',
  'android.permission.NFC_PREFERRED_PAYMENT_INFO': 'NFC 默认支付信息',
  'android.permission.NFC_TRANSACTION_EVENT': 'NFC 交易事件',
  'android.permission.OBSERVE_GRANT_REVOKE_PERMISSIONS': '监听权限变更',
  'android.permission.PERSISTENT_ACTIVITY': '持久活动',
  'android.permission.POST_NOTIFICATIONS': '发送通知',
  'android.permission.PROCESS_OUTGOING_CALLS': '处理拨出电话',
  'android.permission.QUERY_ALL_PACKAGES': '查询所有应用',
  'android.permission.READ_ASSISTANT_APP_SEARCH_DATA': '读取助手搜索数据',
  'android.permission.READ_CALENDAR': '读取日历',
  'android.permission.READ_CALL_LOG': '读取通话记录',
  'android.permission.READ_CONTACTS': '读取联系人',
  'android.permission.READ_EXTERNAL_STORAGE': '读取外部存储',
  'android.permission.READ_HOME_APP_SEARCH_DATA': '读取桌面搜索数据',
  'android.permission.READ_INPUT_STATE': '读取输入状态',
  'android.permission.READ_LOGS': '读取系统日志',
  'android.permission.READ_MEDIA_AUDIO': '读取音频文件',
  'android.permission.READ_MEDIA_IMAGES': '读取图片文件',
  'android.permission.READ_MEDIA_VIDEO': '读取视频文件',
  'android.permission.READ_MEDIA_VISUAL_USER_SELECTED': '读取用户选择的媒体',
  'android.permission.READ_NEARBY_STREAMING_POLICY': '读取附近串流策略',
  'android.permission.READ_PHONE_NUMBERS': '读取电话号码',
  'android.permission.READ_PHONE_STATE': '读取手机状态',
  'android.permission.READ_PROFILE': '读取个人资料',
  'android.permission.READ_SMS': '读取短信',
  'android.permission.READ_SYNC_SETTINGS': '读取同步设置',
  'android.permission.READ_SYNC_STATS': '读取同步统计',
  'android.permission.READ_VOICEMAIL': '读取语音邮件',
  'android.permission.REBOOT': '重启设备',
  'android.permission.RECEIVE_BOOT_COMPLETED': '开机启动',
  'android.permission.RECEIVE_MMS': '接收彩信',
  'android.permission.RECEIVE_SMS': '接收短信',
  'android.permission.RECEIVE_WAP_PUSH': '接收 WAP 推送',
  'android.permission.RECORD_AUDIO': '录音',
  'android.permission.REQUEST_COMPANION_PROFILE_WATCH': '手表伴生设备',
  'android.permission.REQUEST_COMPANION_RUN_IN_BACKGROUND': '伴生应用后台运行',
  'android.permission.REQUEST_COMPANION_START_FOREGROUND_SERVICES_FROM_BACKGROUND': '伴生应用前台服务',
  'android.permission.REQUEST_COMPANION_USE_DATA_IN_BACKGROUND': '伴生应用后台数据',
  'android.permission.REQUEST_DELETE_PACKAGES': '请求删除应用',
  'android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS': '忽略电池优化',
  'android.permission.REQUEST_INSTALL_PACKAGES': '安装应用',
  'android.permission.REQUEST_PASSWORD_COMPLEXITY': '请求密码复杂度',
  'android.permission.RUN_USER_INITIATED_JOBS': '用户发起的作业',
  'android.permission.SCHEDULE_EXACT_ALARM': '精确闹钟',
  'android.permission.SEND_RESPOND_VIA_MESSAGE': '通过消息回复',
  'android.permission.SEND_SMS': '发送短信',
  'android.permission.SET_ALARM': '设置闹钟',
  'android.permission.SET_TIME_ZONE': '设置时区',
  'android.permission.SET_WALLPAPER': '设置壁纸',
  'android.permission.SET_WALLPAPER_HINTS': '设置壁纸提示',
  'android.permission.SIGNAL_PERSISTENT_PROCESSES': '发送信号',
  'android.permission.SPECIAL_USE_FGS_SUBTYPE': '前台服务特殊用途子类型',
  'android.permission.STATUS_BAR': '状态栏',
  'android.permission.SUBSCRIBED_FEEDS_READ': '读取订阅源',
  'android.permission.SUBSCRIBED_FEEDS_WRITE': '写入订阅源',
  'android.permission.SYSTEM_ALERT_WINDOW': '悬浮窗',
  'android.permission.TRANSMIT_IR': '红外传输',
  'android.permission.TURN_SCREEN_ON': '点亮屏幕',
  'android.permission.UNINSTALL_SHORTCUT': '删除快捷方式',
  'android.permission.UPDATE_DEVICE_STATS': '更新设备统计',
  'android.permission.UPDATE_PACKAGES_WITHOUT_USER_ACTION': '静默更新应用',
  'android.permission.USE_BIOMETRIC': '生物识别',
  'android.permission.USE_EXACT_ALARM': '使用精确闹钟',
  'android.permission.USE_FINGERPRINT': '指纹识别',
  'android.permission.USE_FULL_SCREEN_INTENT': '全屏意图',
  'android.permission.USE_SIP': 'SIP 服务',
  'android.permission.UWB_RANGING': '超宽带测距',
  'android.permission.VIBRATE': '振动',
  'android.permission.WAKE_LOCK': '唤醒锁',
  'android.permission.WRITE_APN_SETTINGS': '写入 APN 设置',
  'android.permission.WRITE_CALENDAR': '写入日历',
  'android.permission.WRITE_CALL_LOG': '写入通话记录',
  'android.permission.WRITE_CONTACTS': '写入联系人',
  'android.permission.WRITE_EXTERNAL_STORAGE': '写入外部存储',
  'android.permission.WRITE_GSERVICES': '写入 Google 服务',
  'android.permission.WRITE_PROFILE': '写入个人资料',
  'android.permission.WRITE_SECURE_SETTINGS': '写入安全设置',
  'android.permission.WRITE_SETTINGS': '写入系统设置',
  'android.permission.WRITE_SYNC_SETTINGS': '写入同步设置',
  'android.permission.WRITE_VOICEMAIL': '写入语音邮件',

  // ===== com.android.* =====
  'com.android.alarm.permission.SET_ALARM': '设置闹钟',
  'com.android.browser.permission.READ_HISTORY_BOOKMARKS': '读取浏览器书签',
  'com.android.browser.permission.WRITE_HISTORY_BOOKMARKS': '写入浏览器书签',
  'com.android.calendar.permission.READ': '读取日历',
  'com.android.calendar.permission.WRITE': '写入日历',
  'com.android.contacts.permission.READ_CONTACTS': '读取联系人',
  'com.android.contacts.permission.WRITE_CONTACTS': '写入联系人',
  'com.android.email.permission.READ_ATTACHMENT': '读取邮件附件',
  'com.android.email.permission.PROVIDER': '邮件服务',
  'com.android.launcher.permission.INSTALL_SHORTCUT': '创建快捷方式',
  'com.android.launcher.permission.UNINSTALL_SHORTCUT': '删除快捷方式',
  'com.android.launcher.permission.READ_SETTINGS': '读取桌面设置',
  'com.android.launcher.permission.WRITE_SETTINGS': '写入桌面设置',
  'com.android.permission.GET_INSTALLED_APPS': '获取已安装应用',
  'com.android.providers.calendar.permission.READ_CALENDAR': '读取日历',
  'com.android.providers.calendar.permission.WRITE_CALENDAR': '写入日历',
  'com.android.providers.contacts.permission.READ_CONTACTS': '读取联系人',
  'com.android.providers.contacts.permission.WRITE_CONTACTS': '写入联系人',
  'com.android.providers.downloads.ALL': '下载管理',
  'com.android.providers.media.ALL': '媒体管理',
  'com.android.voicemail.permission.ADD_VOICEMAIL': '添加语音邮件',
  'com.android.voicemail.permission.READ_VOICEMAIL': '读取语音邮件',
  'com.android.vending.BILLING': '应用内计费',
  'com.android.vending.CHECK_LICENSE': '许可证验证',

  // ===== com.google.android.* =====
  'com.google.android.apps.maps.permission.PREFETCH': '地图预缓存',
  'com.google.android.apps.photos.permission.GOOGLE_PHOTOS': 'Google 相册',
  'com.google.android.c2dm.permission.RECEIVE': '推送通知接收',
  'com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE': '安装来源追踪',
  'com.google.android.gms.permission.ACTIVITY_RECOGNITION': '活动识别',
  'com.google.android.gms.permission.AD_ID': '广告 ID',
  'com.google.android.gms.permission.AD_ID_NOTIFICATION': '广告 ID 通知',
  'com.google.android.gms.permission.BIND_ACCOUNTS': '绑定账户',
  'com.google.android.gms.permission.CAR_FUEL': '车辆燃油信息',
  'com.google.android.gms.permission.CAR_INFORMATION': '车辆信息',
  'com.google.android.gms.permission.CAR_MILEAGE': '车辆里程',
  'com.google.android.gms.permission.CAR_SPEED': '车辆速度',
  'com.google.android.gms.permission.CAR_VENDOR_EXTENSION': '车辆扩展信息',
  'com.google.android.gms.permission.CONNECTED_DEVICE': '连接设备',
  'com.google.android.gms.permission.GAMES_DEBUG_SETTINGS': '游戏调试设置',
  'com.google.android.gms.permission.INTERNAL_BROADCAST': '内部广播',
  'com.google.android.gms.permission.NEARBY_DISCOVERY': '附近设备发现',
  'com.google.android.gms.permission.REQUEST_SCREEN_LOCK_COMPLEXITY': '屏幕锁复杂度',
  'com.google.android.gms.permission.SAFETY_NET': 'SafetyNet 认证',
  'com.google.android.googlenavfriend.permission.MAPS_RECEIVE': '地图数据接收',
  'com.google.android.googleapps.permission.GOOGLE_AUTH': 'Google 认证',
  'com.google.android.googleapps.permission.GOOGLE_AUTH.OTHER_SERVICES': 'Google 其他服务',
  'com.google.android.googleapps.permission.GOOGLE_AUTH.youtube': 'YouTube 认证',
  'com.google.android.gtalkservice.permission.GTALK_SERVICE': 'GTalk 服务',
  'com.google.android.permission.INTERNAL_SHOW_POWER_SAVING': '省电模式提示',
  'com.google.android.permission.MAPS_RECEIVE': '地图数据接收',
  'com.google.android.permission.PROVIDER_BACKGROUND': '后台服务',
  'com.google.android.providers.gsf.permission.READ_GSERVICES': '读取 Google 服务',
  'com.google.android.providers.talk.permission.READ_ONLY': '读取 Talk',
  'com.google.android.providers.talk.permission.WRITE_ONLY': '写入 Talk',

  // ===== com.samsung.android.* =====
  'com.samsung.android.app.permission.READ_DUALARMS_SETTINGS': '读取双闹钟设置',
  'com.samsung.android.app.permission.WRITE_DUALARMS_SETTINGS': '写入双闹钟设置',
  'com.samsung.android.camera.permission.REGISTER_EXECUTION': '相机执行',
  'com.samsung.android.ceres.permission.CORE_SERVICE': 'Ceres 核心服务',
  'com.samsung.android.mobileservice.permission.RECEIVE_SMS_BROADCAST': '接收短信广播',
  'com.samsung.android.oneconnect.permission.REGISTER_RECEIVER': 'SmartThings 注册',
  'com.samsung.android.providers.context.permission.WRITE_USE_APP_FEATURE_SURVEY': '使用统计',
  'com.samsung.android.permission.BIND_COEX_SERVICE': '共存服务',
  'com.samsung.android.permission.BIND_SERVICE': '绑定服务',
  'com.samsung.android.permission.LANDING_PAGE': '着陆页',
  'com.samsung.android.permission.READ': '读取（三星）',
  'com.samsung.android.permission.WRITE': '写入（三星）',
  'com.samsung.android.spay.permission.NOTIFY': 'Samsung Pay 通知',
  'com.samsung.android.spay.permission.PAYMENT': 'Samsung Pay 支付',
  'com.sec.android.provider.badge.permission.READ': '读取角标',
  'com.sec.android.provider.badge.permission.WRITE': '写入角标',

  // ===== com.huawei.android.* =====
  'com.huawei.android.launcher.permission.READ_SETTINGS': '读取桌面设置',
  'com.huawei.android.launcher.permission.WRITE_SETTINGS': '写入桌面设置',
  'com.huawei.authentication.identityPermission': '华为身份认证',
  'com.huawei.hms.permission.ACCESS': '华为服务访问',
  'com.huawei.hwid.permission.ACCESS': '华为 ID 访问',
  'com.huawei.hwid.permission.READ_USERSTATE': '读取华为用户状态',
  'com.huawei.hwid.permission.WRITE_USERSTATE': '写入华为用户状态',
  'com.huawei.push.permission.RECEIVE': '华为推送接收',
  'com.huawei.systemmanager.permission.ACCESS_INTERFACE': '系统管理接口',

  // ===== com.xiaomi.* =====
  'com.xiaomi.permission.SEND_PUSH': '小米推送发送',
  'com.xiaomi.xmsf.permission.PAYMENT': '小米支付',
  'com.xiaomi.mipush.RECEIVE_MESSAGE': '小米推送消息',
  'com.xiaomi.passport.permission.PASSPORT_UI_SERVICE': '小米账号服务',

  // ===== com.meizu.* =====
  'com.meizu.c2dm.permission.RECEIVE': '魅族推送接收',
  'com.meizu.flyme.push.permission.RECEIVE': 'Flyme 推送接收',

  // ===== com.oppo.* =====
  'com.oppo.push.permission.RECEIVE': 'OPPO 推送接收',
  'com.coloros.mcs.permission.RECEIVE': 'ColorOS 推送接收',

  // ===== com.vivo.* =====
  'com.vivo.push.permission.RECEIVE': 'vivo 推送接收',

  // ===== com.heytap.* =====
  'com.heytap.mcs.permission.RECEIVE': 'HeyTap 推送接收',

  // ===== com.tencent.* =====
  'com.tencent.mm.permission.MESSAGES': '微信消息',
  'com.tencent.mm.permission.C2DP': '微信推送',
  'com.tencent.bugly.permission.GET': 'Bugly 崩溃上报',
  'com.tencent.tpns.permission.GET': '腾讯推送',

  // ===== 常见第三方 =====
  'cn.jpush.android.permission.JPUSH_MESSAGE': '极光推送',
  'cn.jiguang.api.permission.JPUSH_MESSAGE': '极光推送',
  'com.autonavi.permission.ACCESS_LOCATION': '高德定位',
  'com.amap.api.location.permission.LOCATION': '高德定位',
  'com.taobao.accs.permission.INVOKE': '淘宝 ACCS 服务',
  'com.taobao.agoo.permission.INVOKE': '阿里推送',
  'org.android.agoo.permission.INVOKE': '阿里推送',
  'com.alibaba.permission.FLUTTER_PUSH': '阿里推送',
  'com.umeng.message.permission.INVOKE': '友盟推送',

  // ===== 通用 =====
  'com.google.android.iid.TOKEN_REFRESH': '实例 ID 刷新',
  'com.google.android.instantapps.PROVIDER': '即时应用',
  'com.google.android.providers.settings.permission.READ_GSETTINGS': '读取 Google 设置',
};

/// 获取权限显示名：有中文映射返回中文，否则提取最后两段作为可读名
String getPermissionDisplayName(String perm) {
  final chinese = kPermissionNames[perm];
  if (chinese != null) return chinese;

  // 尝试从权限名提取可读部分
  // android.permission.CAMERA → CAMERA
  // com.google.android.gms.permission.AD_ID → AD_ID
  final parts = perm.split('.');
  if (parts.length >= 2) {
    return parts.last;
  }
  return perm;
}
